CREATE TABLE `userDB`.`user` (
  `ID` INT AUTO_INCREMENT,
  `Fname` VARCHAR(45) NULL,
  `Lname` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Program` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE
);



CREATE TABLE `Posts`.`content` (
  `PostID` INT NOT NULL AUTO_INCREMENT,
  `UserID` VARCHAR(45) NULL,
  `Title` VARCHAR(45) NULL,
  `Content` VARCHAR(65535) NULL,
  PRIMARY KEY (`PostID`));

ALTER TABLE content
ADD COLUMN Course VARCHAR(45) NOT NULL;

ALTER TABLE content
MODIFY COLUMN Content TEXT;
